
//............. Page content

export const teamContent = {
    TEAM_STEP: "Step 2 of 2",
    TEAM_TITLE: "Add Employees",
    TEAM_BACK_BTN: "Back to Organization",
    TEAM_SKIP_BTN: "Skip for now",
    TEAM_ADD_MEMBERS: "Add team members",
    TEAM_TEXT: " Invite your colleagues to join your organization",
    TEAM_EMAIL_INVITE: "Email Invites",
    TEAM_BULK_UPLOAD: "  Bulk Upload",
    TEAM_NAME_PLACEHOLDER: "Full Name",
    TEAM_EMAIL_PLACEHOLDER: "Email address",
    TEAM_SELECT_ROLE: "Select Role",
    TEAM_SELECT_EMPLOYEE: "Employee",
    TEAM_SELECT_ADMIN: "Admin",
    TEAM_SELECT_MANAGER: "Manager",
    TEAM_ADD_ANOTHER_BTN: "Add another",
    TEAM_INVITATION_BTN_LOADER: "Invitations Sending...",
    TEAM_SEND_INVITATION_BTN: "Send Invitations",
    TEAM_FOOTER_TEXT: "Invitations will be sent via email with instructions to join your organization.",
    TEAM_BULK_REPORT_TEXT: "Data Validation Report",
    TEAM_BULK_UPLOAD_TEXT: "Click to upload CSV",
    TEAM_BULK_DRAG_TEXT: "or drag and drop",
    TEAM_SUCCESS_MSG: "Team member added successfully",
    TEAM_BULK_FILE_SUCCESS: "File uploaded successfully.",
    TEAM_REQUIRED: "Name is required",
    TEAM_INVALID_NAME: "Invalid name",
    TEAM_EMAIL_REQUIRED: "Email is required",
    TEAM_INVALID_EMAIL: "Invalid email format",
    TEAM_ROLE_REQUIRED: "Role is required",
    TEAM_FAILED_ERROR: "Failed to skip onboarding. Please try again.",
    TEAM_BULK_REQUIRED: "Name, Email, and Role required fields",
    TEAM_BULK_INVALID_NAME: "Invalid name",
    TEAM_BULK_DUPLICATE_EMAIL: "Duplicate email",
    TEAM_BULK_INVALID_ROLE: "Invalid role",
    TEAM_BULK_MISSING_ERROR: "Missing",
    EMAIL_REGEX: /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/,
    TEAM_BULK_INVALID_FILE: "Invalid file type. Please upload a valid file.",
    TEAM_NAME_REGEX: /^[A-Za-z]+(?: [A-Za-z]+)*$/,
}