
 export const loginContent = {
     LOGIN_PAGE_TITLE : "Login",
     LOGIN_PAGE_SUBTITLE : "Enter your credentials to access your account",
     GOOGLE_BUTTON_TEXT : "Google",
     EMAIL_BUTTON_TEXT : "Continue with Email",
     SIGNUP_LINK_TEXT : "Sign up",
     FORGOT_PASSWORD_LINK_TEXT : "Forgot password?",
     EMAIL_LABEL : "Email",
     EMAIL_PLACEHOLDER : "you@example.com",
     PASSWORD_LABEL : "Password",
     PASSWORD_PLACEHOLDER : "Password",
     CONFIRM_PASSWORD_PLACEHOLDER : "Confirm Password",
     PASSWORDS_MISMATCH_ERROR : "Passwords do not match.",
     DIVIDER_TEXT : "OR CONTINUE WITH",
     NO_ACCOUNT_TEXT : "Didn't have an account? ",
     REQUIRED_EMAIL_ERROR : "Please enter your email",
     REQUIRED_PASSWORD_ERROR : "Please enter your password",
     INVALID_PASSWORD_ERROR : "Password must be at least 8 characters, with 1 uppercase letter and 1 special character.",
     INVALID_EMAIL_ERROR : "Please enter a valid email address.",
     LOADING_TEXT : "Logging in",
     LOGIN_SUCCESS_TOAST : "User login successfully",
     USER_NOT_FOUND_TOAST : "User not found",
     SERVER_ERROR_TOAST : "Server error",
     EMAIL_REGEX : /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
     PASSWORD_REGEX : /^(?=.*[A-Z])(?=.*\W)(?=.*\d).{8,}$/,
 }