/**
 * Permission constants for the application
 * These match the permission names in the backend
 */

// Timer permissions
export const TIMER_PERMISSIONS = {
  CREATE_TIMER: "CREATE_TIMER",
  READ_TIMER: "READ_TIMER",
  READ_TIMER_OTHERS: "READ_TIMER_OTHERS",
  UPDATE_TIMER: "UPDATE_TIMER",
  DELETE_TIMER: "DELETE_TIMER",
  UPDATE_TIMER_OTHERS: "UPDATE_TIMER_OTHERS",
  DELETE_TIMER_OTHERS: "DELETE_TIMER_OTHERS",
  DELETE_TIMER_NOTE: "DELETE_TIMER_NOTE",
}

// Client permissions
export const CLIENT_PERMISSIONS = {
  CREATE_CLIENT: "CREATE_CLIENT",
  READ_CLIENT: "READ_CLIENT",
  UPDATE_CLIENT: "UPDATE_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",
}

// Project permissions
export const PROJECT_PERMISSIONS = {
  CREATE_PROJECT: "CREATE_PROJECT",
  READ_PROJECT: "READ_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
}

// Task permissions
export const TASK_PERMISSIONS = {
  CREATE_TASK: "CREATE_TASK",
  READ_TASK: "READ_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
}

// Team member permissions
export const TEAM_PERMISSIONS = {
  CREATE_TEAM_MEMBER: "CREATE_TEAM_MEMBER",
  READ_TEAM_MEMBER: "READ_TEAM_MEMBER",
  UPDATE_TEAM_MEMBER: "UPDATE_TEAM_MEMBER",
  DELETE_TEAM_MEMBER: "DELETE_TEAM_MEMBER",
}

// Organization permissions
export const ORGANIZATION_PERMISSIONS = {
  READ_ORGANIZATION: "READ_ORGANIZATION",
  UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
}

// Report permissions
export const REPORT_PERMISSIONS = {
  VIEW_REPORTS: "VIEW_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
}

// Settings permissions
export const SETTINGS_PERMISSIONS = {
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
}
