
export const registerContent = {
    REGISTER_PAGE_TITLE: "Create an account",
    REGISTER_PAGE_SUBTITLE: "Choose how you'd like to",
    REGISTER_PAGE_SUBTITLE_SIGN_UP: "sign up",
    SET_PASSWORD_TITLE: "Set your password",
    SET_PASSWORD_SUBTITLE: "Choose a secure password for your account",
    VERIFY_CODE_TITLE: "Enter Verification Code",
    VERIFY_CODE_SUBTITLE: "We've sent a 6-digit code to ",
    GOOGLE_BUTTON_TEXT: "Continue with Google",
    EMAIL_BUTTON_TEXT: "Continue with Email",
    CREATE_ACCOUNT_BUTTON_TEXT: "Create Account",
    CREATING_ACCOUNT_TEXT: "Creating Account",
    VERIFY_CODE_BUTTON_TEXT: "Verify Code",
    VERIFYING_CODE_TEXT: "Verifying",
    RESEND_CODE_TEXT: "Resend Code",
    RESENDING_CODE_TEXT: "Resending",
    EMAIL_PLACEHOLDER: "name@example.com",
    NOT_EMAIL_EXIST : "Email is required. Please go back to the registration page.",
    PASSWORD_PLACEHOLDER: "Password",
    CONFIRM_PASSWORD_PLACEHOLDER: "Confirm Password",
    DIVIDER_TEXT: "OR CONTINUE WITH",
    INVALID_EMAIL_ERROR: "Please enter a valid email address.",
    EDIT_EMAIL_MESSAGE: "Go back to edit your email",
    EMPTY_PASSWORD_ERROR: "Please enter your password.",
    PASSWORD_LENGTH_ERROR: "Password must be at least 8 characters.",
    PASSWORD_UPPERCASE_ERROR: "Must include an uppercase letter.",
    PASSWORD_NUMBER_ERROR: "Must include a number.",
    PASSWORD_SPECIAL_CHAR_ERROR: "Must include a special character.",
    PASSWORDS_MISMATCH_ERROR: "Passwords do not match.",
    EMPTY_CODE_ERROR: "Please fill in all the fields.",
    REGISTER_SUCCESS_TOAST: "User registered successfully",
    USER_EXISTS_TOAST: "User already exists",
    SERVER_ERROR_TOAST: "Server error",
    USER_VERIFIED_TOAST: "User verified successfully",
    USER_ALREADY_VERIFIED_TOAST: "User already verified",
    CODE_SENT_TOAST: "Verification code sent successfully",
    INVALID_PASSWORD_ERROR: "Password must be at least 8 characters, with 1 uppercase letter and 1 special character.",
    NOT_RECEIVE_CODE_TEXT: "Didn't receive the code? ",
    PASSWORD_VERY_WEAK: "Very Weak",
    PASSWORD_WEAK: "Weak",
    PASSWORD_MEDIUM: "Medium",
    PASSWORD_STRONG: "Strong",
    PASSWORD_VERY_STRONG: "Very Strong",
    PASSWORD_STRENGTH_TEXT: "Password Strength:",
    EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    PASSWORD_REGEX : /^(?=.*[A-Z])(?=.*\W)(?=.*\d).{8,}$/,
}