
export const userProfileContent = {
    PROFILE_HEADING : "User Profile",
    PROFILE_HEADING_TEXT : "View and manage user information",
    UPLOAD_PHOTO_TEXT: "Upload Photo",
    FULL_NAME_LABEL : "Name",
    FULL_NAME_PLACEHOLDER : "Enter your full name",
    ROLE_LABEL : "User Role",
    SELECT_ROLE : "Select Role",
    SELECT_USER_VALUE : "User",
    SELECT_ADMIN_VALUE : "Admin",
    SELECT_EMPLOYEE_VALUE : "Employee",
    SELECT_MANAGER_VALUE : "Manager",
    LOADING_BUTTON_TEXT: "Saving...",
    BUTTON_TEXT : "Save Changes",
    CANCEL_BUTTON_TEXT : "Cancel",
    REQUIRED_NAME : "Name is required",
    INVALID_NAME: "Invalid name",
    EMAIL_REQUIRED  : "Email is required",
    VALID_EMAIL : "Please enter a valid email address",
    INVALID_IMAGE : "Please upload a valid image (JPEG, PNG, or GIF).",
    FAILED_UPLOAD_ERROR : "Something went wrong",
    SERVER_ERROR : "Error uploading image:",
    SOMETHING_SERVER_ERROR : "Something went wrong during image upload",
    FAILED_UPLOAD_PROFILE : "Failed to update profile",
    SUCCESS_IMAGE_UPLOAD : "Image uploaded successfully",
    PROFILE_UPDATE_SUCCESS : "User profile updated successfully",
    LOGOUT : "Logout",
}